AWSTemplateFormatVersion: '2010-09-09'
Description: Build pipeline for java-demoapp

Resources:
  JavaDemoApp:
    Type: AWSSamples::CodePipeline::MultiarchECS::MODULE
    Properties:
      SourceRepo: otterley/java-demoapp
      BranchName: master
      ImageRepository: !ImportValue java-demoapp-RepositoryUri
      CodeStarConnectionArn: arn:aws:codestar-connections:us-west-2:523443631803:connection/aafa4a94-2aed-40b0-a3bb-fc33d238a5f0
      BuildAndPushImageBuildspecPath: build/buildspec.yml
      TestImageBuildspecPath: build/buildspec-test.yml
      BuildAndPushManifestBuildspecPath: build/buildspec-manifest.yml
      DeployBuildspecPath: deploy/aws/buildspec-deploy.yml
